import type { Project } from "@/lib/projects";

export const projects: Project[] = [
  {
    slug: "local-llms",
    title: "local-llms",
    blurb: "Practical local model usage, tooling, and infrastructure.",
    tags: ["Python", "Local LLMs", "Tooling"],
    stars: 1,
    repo: "https://github.com/ajmeese7/local-llms",
  },
  {
    slug: "readme-ascii",
    title: "readme-ascii",
    blurb: "Web frontend using Figlet.js to turn text into ASCII-art images for GitHub READMEs.",
    tags: ["JavaScript", "ASCII", "GitHub"],
    stars: 86,
    repo: "https://github.com/ajmeese7/readme-ascii",
    live: "https://ajmeese7.github.io/readme-ascii/",
  },
  {
    slug: "hermes-multi-user-skill",
    title: "hermes-multi-user",
    blurb: "Enable multiple Hermes Agent personalities, cementing OpenClaw feature parity.",
    tags: ["Hermes Agent", "Skill"],
    stars: 11,
    repo: "https://github.com/ajmeese7/hermes-multi-user-skill",
    blog: "https://blog.aaronmeese.com/how-i-set-up-multi-user-ai-agents-with-hermes-and-you-can-too-648b52fe20e9",
  },
  {
    slug: "termblog",
    title: "termblog",
    blurb: "Self-hosted, terminal-themed blogging platform written in Go.",
    tags: ["Go", "Self-hosted", "Blog"],
    stars: 2,
    repo: "https://github.com/ajmeese7/termblog",
    live: "https://termblog.com",
  },
  {
    slug: "reading-log",
    title: "reading-log",
    blurb: "Log articles I consume to an RSS feed via Cloudflare Workers.",
    tags: ["TypeScript", "Cloudflare", "RSS"],
    stars: 1,
    repo: "https://github.com/ajmeese7/reading-log",
  },
  {
    slug: "tools",
    title: "tools",
    blurb: "Assortment of boutique useful scripts worth sharing.",
    tags: ["Python", "Claude"],
    stars: 1,
    repo: "https://github.com/ajmeese7/tools",
  },
  {
    slug: "design-experiments",
    title: "design-experiments",
    blurb: "Experimental design concepts to explore creative visual representation.",
    tags: ["Design", "Liminal Spaces", "Experiment"],
    stars: 1,
    repo: "https://github.com/ajmeese7/design-experiments",
  },
  {
    slug: "347am",
    title: "347am",
    blurb: "A small site that only fully exists during the liminal hours of the night.",
    tags: ["Liminal Spaces", "Experiment"],
    stars: 1,
    repo: "https://github.com/ajmeese7/347am",
  },
];
